### ISSUE TITLE
MapConfig.SetDefault doesn't properly set up nested keys

### ISSUE THREAD

**Issue by silasdavis** [tendermint/go-config#1]
This commit adds support for nested keys: https://github.com/tendermint/go-config/commit/0943f92a414a30d755d59a7feb26b5713a6e7cb3

But, `SetDefault` doesn't honour this by producing a multi-dimensional array when given a string `"key.with.dots.in"`: https://github.com/tendermint/go-config/blob/master/config.go#L95

**Comment by ebuchman** [comment]
sorry bout that. fixed: https://github.com/tendermint/go-config/commit/643bb63c3e09e9c7bbb7aca4858667cf925c4210
